# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWG4kR1lL_qTCPf_tM7VFG1UdM9lg8oQ
"""

import pandas as pd
import streamlit as st

st.title("Buscador de Jugadores")

df = pd.read_excel("jugadores.xlsx")

rut = st.text_input("Ingrese RUT")

if st.button("Buscar"):
    resultado = df[df['RUT'].astype(str) == rut]

    if not resultado.empty:
        st.write(resultado)
    else:
        st.warning("No encontrado")